---
apiVersion: v1
kind: Namespace
metadata:
  name: xray
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: xray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: app
          image: pksinghus/feapp
          ports:
            - containerPort: 8080
          env:
            - name: "COLOR_HOST"
              value: "color:8080"
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: xray-service.default:2000
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: xray
  labels:
    app: front
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color 
  namespace: xray
  labels:
    app: color
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
      version: blue
  template:
    metadata:
      labels:
        app: color
        version: blue
    spec:
      containers:
        - name: app
          image: pksinghus/colorapp
          ports:
            - containerPort: 8080
          env:
            - name: "COLOR"
              value: "blue"
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: xray-service.default:2000
---
apiVersion: v1
kind: Service
metadata:
  name: color
  namespace: xray
  labels:
    app: color
    version: blue
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: color
    version: blue